#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from argparse import ArgumentParser
import os, logging, asyncio, sys
from re import DOTALL, findall
from requests import get
from pathlib import Path
from shutil import copyfile, which
import bart
from bart.scripts.version import __version__
from bart.scripts.kma import index

__author__ = "Tom Stanton"
__license__ = "MIT"
__maintainer__ = "Tom Stanton"
__email__ = "tomdstanton@gmail.com"
__status__ = "Development"

def parse_args():
    parser = ArgumentParser(add_help=False, usage="bart-update [options]",)
    parser.print_usage = parser.print_help
    options = parser.add_argument_group('--options [defaults]')
    options.add_argument('-s', action='store_true', default=False, help='print available MLST schemes')
    options.add_argument('-S', action='store_true', default=False, help='-s with genes')
    options.add_argument('-p', action='store_true', default=False, help='update pubMLST schemes')
    options.add_argument('-a', metavar='', nargs='*', type=Path, help='path to custom scheme fasta and csv')
    options.add_argument('-r', metavar='', type=str, nargs='*', help='name of scheme(s) to remove')
    options.add_argument('-amr', action='store_true', default=False, help='update AMR index')
    options.add_argument('-h', action="help", help='show this help message and exit')
    if len(sys.argv) == 1:
        sys.exit(parser.print_help())
    args = parser.parse_args()
    return args


def main():
    db_path = f'{os.path.dirname(bart.__file__)}/db'
    os.makedirs(db_path, exist_ok=True)
    os.makedirs(f'{db_path}/indexes', exist_ok=True)
    os.makedirs(f'{db_path}/mapping', exist_ok=True)
    logger = logging.getLogger('root')
    logging.basicConfig(format='%(asctime)s | %(message)s', datefmt="%H:%M:%S")
    logger.setLevel(logging.DEBUG)
    if which('kma') is None:
        sys.exit(logger.error('kma not found'))
    logging.getLogger('urllib3').setLevel(logging.WARNING)
    args = parse_args()

    if args.s:
        d = [f.name.split('.')[0] for f in os.scandir(f'{db_path}/mapping/')]
        sys.exit(print(*sorted(d), sep="\n"))

    if args.S:
        d = []
        for f in os.scandir(f'{db_path}/mapping/'):
            with open(f) as file:
                l = file.readline()
                d.append(l.replace(l.split('\t')[0], f.name.split('.')[0]).strip())
        sys.exit(print(*sorted(d), sep="\n"))

    logger.info(f'this is bart {__version__} by {__author__}')
    logger.info(f'running on {sys.platform} with Python '
                f'{str(sys.version_info[:3])[1:-1].replace(", ", ".")}')

    if args.a:
        names = []
        logger.info(f'adding scheme from: {str(args.a)}')
        for i in args.a:
            if os.path.isfile(i):
                names.append(os.path.basename(i).split('.', -1)[0])
                with open(i, 'rb') as f:
                    first = next(f).decode()
                if first.startswith('>'):
                    fasta = i
                    logger.info(f'{i} is a valid fasta file')
                elif first.startswith('ST\t'):
                    mapping = i
                    logger.info(f'{i} is a valid mapping file')
                else:
                    break
            else:
                sys.exit(logger.error(f'{i} is not a valid file'))

        # remove dupes to see if name is the same
        names = list(dict.fromkeys(names))

        if len(names) > 1:
            sys.exit(logger.error(f'files need to have same names, not: {names[0]}'))
        copyfile(mapping, f'{db_path}/mapping/{names[0]}.tab')
        with open(fasta, 'r') as f:
            index(f.read(), f'{db_path}/indexes/{names[0]}')

    if args.r:
        for name in args.r:
            logger.info(f'removing {db_path}/mapping/{name}.tab')
            os.remove(f'{db_path}/mapping/{name}.tab')
            for i in ['.comp.b', '.seq.b', '.length.b', '.name']:
                logger.info(f'removing {db_path}/indexes/{name}{i}')
                os.remove(f'{db_path}/indexes/{name}{i}')

    if args.p:
        def background(f):
            def wrapped(*args, **kwargs):
                return asyncio.get_event_loop().run_in_executor(None, f, *args, **kwargs)
            return wrapped

        @background
        def build_mlst(s):
            logging.getLogger("requests").setLevel(logging.WARNING)
            scheme, urls = s.split('\n'), []
            name = scheme[0].replace(' ', '_').replace('/', '_').strip('.')
            for l in scheme:
                if any(ft in l for ft in ['csv', 'fasta']):
                    urls.append(l.split('>')[1].split('<')[0])
            with open(f'{db_path}/mapping/{name}.tab', 'ab') as f:
                f.write(get(urls[0]).content)
            logger.info(f'written scheme map to {db_path}/mapping/{name}.tab')
            i = ''
            for url in urls[1:]:
                i += get(url).text
            index(i, f'{db_path}/indexes/{name}')

        # this deletes files if they already exist
        [f.unlink() for f in Path(f'{db_path}/mapping/').glob("*") if f.is_file()]
        for species in findall('<species>(.*?)</species>', get('https://pubmlst.org/static/data/dbases.xml').text, DOTALL):
            build_mlst(species)

    if args.amr:
        fasta = []
        for i in get('https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/latest/AMR_CDS').text.split('\n'):
           if i.startswith('>'):
               logger.info(f"adding {i.split('|')[5]}")
               fasta.append(f">{i.split('|')[5]} {i.split('|')[7].split(' ')[0]}")
           else: fasta.append(i)
        index('\n'.join(fasta), f'{db_path}/indexes/amr')

if __name__ == '__main__':
    main()
